services:
  mysql:
    image: mysql:8.0
    container_name: wedding-site-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wedding_db
      MYSQL_USER: wedding_user
      MYSQL_PASSWORD: wedding_password
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
